version: "3.9"

services:
  flowise:
    image: "133981716884.dkr.ecr.us-west-2.amazonaws.com/flowise:m-2.2.4"
    ports:
      - "4000:4000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # 其他 Flowise 环境变量
    volumes:
      - ./.env:/app/packages/server/.env # 将本地 .env 文件挂载到容器指定目录
    networks:
      - mynetwork

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - mynetwork

networks:
  mynetwork: